services:
  - type: web
    name: neurogait-ai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.api.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
